import type { Metadata } from "next";
import { montserrat } from "./ui/fonts";
import "./ui/global.css";
import Header from "./header";
import Footer from "./footer";

export const metadata: Metadata = {
  title: "User List",
  description: "Generated by Fernanda Cancino",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element  {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased dark:bg-gray-900 dark:text-white`}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow p-4 flex flex-col items-center justify-center mx-auto w-full max-w-4xl">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}